name = "Silver Lining"
author = "omo50, Adrenix, BlueStaggo, icanttellyou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09cd52e503118f266cf8d42afe9832b04d8e7bb085cf0e3d8e104399932b3fe3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
