name = "Silver Lining"
author = "omo50, Adrenix, BlueStaggo, icanttellyou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77e5de60140568b922da882e09eef6271b7bdbae2ebe648bdf7555fa446ac51e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
