name = "Silver Lining"
author = "omo50, Adrenix, BlueStaggo, icanttellyou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8686f22dcf4215912936d65864bd82a117ac45d3bfb242e789a95a692d7253d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
