name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  auto-update:
    runs-on: codeberg-small

    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Update
        run: |
          sudo chmod +x update-all.sh
          ./update-all.sh

      - name: Commit Updates
        uses: https://github.com/EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
